### ISSUE TITLE
Outdated benchmarks

### ISSUE THREAD

**Issue by buger** [krakend/krakend-documentation#71]
Hi there! 

I'm your colleague from Tyk.io :)

I noticed that benchmarks you have on the website are 4-5 years old (if we talking about https://github.com/varnish/api-gateway-benchmarks). And on your comparison page, you also say that it was last run "August 2015". 

Since you mention this numbers also on your landing page, it would be at least fair to re-run benchmarks with a new Kong and Tyk versions. At the moment such old tests work against you.

I'm happy to help with the benchmarking suite if you will be interested!

Cheers!

**Comment by alombarte** [comment]
Hi @buger ,

Thanks for stopping by, I am glad you opened this issue. It's not the first time we've got contact from Tyk regarding the performance benchmarks. Today you are not a salesperson with "an opinion" on the resulting numbers, we are making progress :)

Jokes aside, I am happy that you are volunteering for possible work on the matter. So, have my appreciation for the gesture in advance and let me give you some context and actionable items.

The tests are open-sourced and can be rerun, repeated, and updated by anyone; in fact, they extend a performance benchmark from Varnish. You are more than welcome to make a [pull request](https://github.com/devopsfaith/api-gateway-benchmarks).

When we talk about performance with the community, customers, and prospects, our recommendation is always that their teams run their tests using their case and not believe any marketing materials from anyone (not even ours).  Benchmarking is not a white or black thing as you are well aware, and we recommend to each adopting company to run tests applying their use cases (e.g., with aggregation, or authorization, or whatever they need). Happily for us, we won in every single scene so far.

From a dedication perspective, it takes a while preparing such tests: make the code, draw the graphs, update the tables, and reflect the changes in the website. Our resources are more limited (compared to Tyk or Kong), and the business value of this action you are requesting is clear to me: zero.

Despite this, if you are willing to collaborate, maybe we can do something that benefits us mutually and brings actual value to users. An idea, we could elaborate on a richer benchmarking (using different scenarios) and publish the results jointly on the Tyk and KrakenD websites. If you have more ideas, you have my complete attention (you can contact me by email at "albert" plus domain name)

And finally, you are right. Outdated benchmarks work against us because KrakenD is now faster :)

Thanks

**Comment by alombarte** [comment]
Hi @buger, just pinging before closing the issue. Are you still interested in benchmarking?

**Comment by buger** [comment]
Hi! Yes, I realized that I missed the notification! 
We will try to make an action based on that!

**Comment by alombarte** [comment]
Thanks! My email is open if you want to arrange anything off-line

**Comment by alombarte** [comment]
Hello @buger, are you still interested in working into this?

**Comment by alombarte** [comment]
Closed for inactivity
